export enum Skill {
    FEVER = "FEVER",
    CARDIOLOGY = "CARDIOLOGY",
    PAEDIATRICS = "PAEDIATRICS",
    NEUROLOGY = "NEUROLOGY",
    ONCOLOGY = "ONCOLOGY",
    DERMATOLOGY = "DERMATOLOGY",
    MEDICINE = "MEDICINE"
}